trustbloc/sidetree-fabric

.ci-properties, Makefile, cmd/sidetree-server/main.go, images/sidetree-fabric/Dockerfile, test/bddtests/fixtures/.env, test/bddtests/fixtures/config/client/config.yaml, test/bddtests/fixtures/config/client/protocol.json, test/bddtests/fixtures/docker-compose.yml
=> ci: Build sidetree fabric image

.gitignore, Makefile, go.mod, scripts/copycc.sh, test/bddtests/bddtests_test.go, test/bddtests/features/e2e.feature
=> ci: build sidetree txn cc

cmd/chaincode/cas/client.go, cmd/chaincode/cas/client_test.go, cmd/chaincode/doc/META-INF/statedb/couchdb/collections/docs/indexes/indexID.json, cmd/chaincode/doc/doc.go, cmd/chaincode/doc/doc_test.go, cmd/chaincode/mocks/mockstub.go, scripts/copycc.sh
Create document user chain code that will be used to store and read document operations. It will also have capability to query all operations for document with specified ID.
Closes #29
=> feat: Document CC

pkg/context/context.go, pkg/context/store/client.go, pkg/context/store/client_test.go, pkg/context/store/mocks/channel.go
Store client will read document operations for specified document ID.
Closes #31
=> feat: Store Client (Fabric)

go.mod, go.sum, pkg/observer/notifier/notifier.go, pkg/observer/notifier/notifier_test.go, pkg/observer/observer.go, pkg/observer/observer_test.go, test/bddtests/fixtures/fabric/peer/cmd/go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> feat: Use sidetree-core-go generic observer

.golangci.yml, pkg/observer/observer.go, pkg/observer/observer_test.go, scripts/check_lint.sh
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>
=> ci: GolangCI Lint - Update docker image source, fix lint errors and and remove webhook config

go.mod, go.sum, test/bddtests/fixtures/fabric/peer/cmd/go.mod, test/bddtests/fixtures/fabric/peer/cmd/go.sum, test/bddtests/fixtures/testdata/didDocument.json, test/bddtests/fixtures/testdata/didDocument2.json, test/bddtests/go.mod, test/bddtests/go.sum, test/bddtests/restclient/sender.go
=> chore: Update to latest sidetree-core-go and sidetree-node revision

README.md
=> ci: update readme build badge to azp

README.md, ci/azure-pipelines.yml, test/bddtests/bddtests_test.go
=> chore: Push sidetree image using azure

go.mod, go.sum, test/bddtests/fixtures/fabric/peer/cmd/go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Update sidetree-core-go revision to v0.1.0

README.md
Signed-off-by: Igogrek <igogrek@gmail.com>
Some basic information on how to run tests and docker-compose for this repo
=> docs: update readme with docker-compose info

ci/version_var.sh
=> chore: Change release version to 0.1.2

ci/azure-pipelines.yml
=> chore: push images to docker.pkg.github.com

cmd/chaincode/doc/doc.go, cmd/peer/go.sum, go.mod, go.sum, pkg/context/store/client.go, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Update to latest sidetree-core
Closes #125
=> chore: Update to latest sidetree-core

ci/version_var.sh
=> chore: Change version to 0.1.3

cmd/chaincode/doc/doc.go, cmd/chaincode/doc/doc_test.go, test/bddtests/features/sidetreetxn.feature
Document CC is required for the creation of collection and database. It is not required for logic.
Closes #134
=> chore: Remove duplicate document CC code

cmd/peer/go.sum, go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/fixtures/testdata/didDocument.json, test/bddtests/fixtures/testdata/didDocument2.json, test/bddtests/go.mod, test/bddtests/go.sum, test/bddtests/restclient/sender.go
Update to the latest sidetree-core
Closes #139
=> feat: update to latest sidetree-core (create request changed)

cmd/peer/go.sum, go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Create request is no longer signed request. Update to latest sidetree-core.
Closes #146
=> chore: Update sidetree-core (create no longer signed request)

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
Add update document BDD test (via JSON patch)
Closes #155
=> test: Add update document via JSON patch

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/features/file-handler.feature, test/bddtests/features/step_definitions/filehandler_steps.js, test/bddtests/filehandler_steps.go, test/bddtests/fixtures/docker-compose.yml, test/bddtests/go.mod, test/bddtests/go.sum
=> test: Added BDD test for file index update

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/fixtures/testdata/recover.json, test/bddtests/go.mod, test/bddtests/go.sum
Add bdd test for document recovery
Closes #167
=> feat: Add document recovery

cmd/peer/go.sum, go.mod, go.sum, pkg/httpserver/server.go
=> feat: Add cors (https://www.w3.org/TR/cors/)

pkg/httpserver/server.go, pkg/httpserver/server_test.go, pkg/peer/config/peerconfig.go, pkg/peer/config/peerconfig_test.go, pkg/peer/mocks/restconfig.gen.go, pkg/peer/sidetreesvc/provider.go, pkg/peer/sidetreesvc/restsvc.go, test/bddtests/features/did-sidetree.feature, test/bddtests/features/file-handler.feature, test/bddtests/fixtures/docker-compose.yml, test/bddtests/go.mod, test/bddtests/go.sum, test/bddtests/restclient/sender.go
=> feat: Enable tls for sidetree server

cmd/peer/go.sum, go.mod, go.sum, pkg/context/store/client.go, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Operation model changed
Closes #184
=> chore: update sidetree-core

pkg/config/config.go, pkg/config/mocks/sidetreeconfigservice.gen.go, pkg/peer/config/constants.go, pkg/peer/config/dcashandlervalidator.go, pkg/peer/config/dcashandlervalidator_test.go, pkg/peer/config/service.go, pkg/peer/config/service_test.go, pkg/peer/sidetreesvc/channelctrl.go, pkg/peer/sidetreesvc/channelctrl_test.go, pkg/rest/dcashandler/config.go
- Defined the DCAS handler configuration
- Modified the channel service controller to load the DCAS handler configuration.
Note: The actual handlers will be implemented in a subsequent patch.
closes #199
=> feat: Added DCAS handler configuration

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
Included:
-- handle key usage
-- revoke renamed to deactivate
Closes  #207
=> chore: Update sidetree-core - handle key usage / deactivate

pkg/client/blockchainclient.go, pkg/observer/common/providers.go, pkg/observer/mocks/bcclient.gen.go, pkg/peer/sidetreesvc/channelctrl.go, pkg/peer/sidetreesvc/channelctrl_test.go, pkg/peer/sidetreesvc/handlers.go, pkg/rest/blockchainhandler/model.go, pkg/rest/blockchainhandler/timehandler.go, pkg/rest/blockchainhandler/timehandler_test.go, test/bddtests/features/blockchain-handler.feature
=> feat: Added REST endpoint for blockchain time by hash

Makefile, pkg/peer/config/service.go, pkg/peer/sidetreesvc/channelctrl.go, pkg/peer/sidetreesvc/channelctrl_test.go, pkg/peer/sidetreesvc/handlers.go, pkg/rest/blockchainhandler/config.go, pkg/rest/blockchainhandler/timehandler_test.go, pkg/rest/blockchainhandler/versionhandler.go, pkg/rest/blockchainhandler/versionhandler_test.go, pkg/rest/dcashandler/model.go, pkg/rest/versionhandler/model.go, pkg/rest/versionhandler/versionhandler.go, pkg/rest/versionhandler/versionhandler_test.go, test/bddtests/features/blockchain-handler.feature
The /blockchain/version endpoint returns the Fabric version.
closes #209
=> feat: Added blockchain version REST endpoint

cmd/peer/go.sum, go.mod, go.sum, pkg/filehandler/retrievehandler.go, pkg/filehandler/retrievehandler_test.go, pkg/filehandler/validator.go, pkg/filehandler/validator_test.go, pkg/httpserver/server_test.go, pkg/mocks/documentresolver.gen.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/file-handler.feature, test/bddtests/filehandler_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Sidetree core now returns result set instead of document
Also, add file handler transform to external document
Closes #215
=> chore: sidetree-core - result set + file handler transform

pkg/peer/sidetreesvc/channelctrl.go, pkg/peer/sidetreesvc/channelctrl_test.go, pkg/rest/blockchainhandler/blockchainerror.go, pkg/rest/blockchainhandler/blockchainscanner.go, pkg/rest/blockchainhandler/blockchainscanner_test.go, pkg/rest/blockchainhandler/blockscanner.go, pkg/rest/blockchainhandler/blockscanner_test.go, pkg/rest/blockchainhandler/model.go, pkg/rest/blockchainhandler/responsewriter.go, pkg/rest/blockchainhandler/responsewriter_test.go, pkg/rest/blockchainhandler/timehandler.go, pkg/rest/blockchainhandler/transactionshandler.go, pkg/rest/blockchainhandler/transactionshandler_test.go, pkg/rest/dcashandler/retrievehandler.go, test/bddtests/features/blockchain-handler.feature
=> feat: Blockchain transactions REST endpoint with 'hash' and 'since'

cmd/peer/go.sum, go.mod, go.sum, pkg/context/store/client.go, pkg/filehandler/validator.go, pkg/filehandler/validator_test.go, pkg/httpserver/server_test.go, pkg/observer/observer_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/filehandler_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Sidetree-core has been updated:
-- model/tag/patch changes
-- JWK is enforced for public key format
Closes #224
=> chore: update sidetree-core - model/tags renaming, JWK enforced

cmd/peer/go.sum, go.mod, go.sum, pkg/context/protocol/client_test.go, pkg/peer/config/service_test.go, pkg/peer/config/sidetreevalidator.go, pkg/peer/config/sidetreevalidator_test.go, pkg/peer/init_test.go, pkg/peer/sidetreesvc/channelctrl_test.go, pkg/peer/sidetreesvc/context_test.go, pkg/peer/sidetreesvc/provider_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/fixtures/config/client/protocol.json, test/bddtests/fixtures/config/fabric/invalid-hash-algorithm.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_4.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_5.json, test/bddtests/go.mod, test/bddtests/go.sum
Resolve with initial state, config: max operation byte size -> max delta byte size
Closes #234
=> chore: Update sidetree-core - Resolve with initial state

cmd/peer/go.sum, go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/blockchain-handler.feature, test/bddtests/features/did-sidetree.feature, test/bddtests/features/step_definitions/sidetree_steps.js, test/bddtests/fixtures/config/fabric/mychannel-sidetree-config-org1.json, test/bddtests/fixtures/config/fabric/mychannel-sidetree-config-org2.json, test/bddtests/go.mod, test/bddtests/go.sum
=> feat: Renamed Sidetree update endpoint to /operations

.gitignore, ci/azure-pipelines.yml, scripts/integration.sh, test/bddtests/features/did-sidetree.feature, test/bddtests/features/sidetreetxn.feature
=> test: Run BDD tests in parallel

cmd/peer/go.sum, go.mod, go.sum, pkg/httpserver/server_test.go, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Added server side validations for operations
Closes #242
=> chore: update sidetree-core - server side validations for operations

ci/azure-pipelines.yml
Run all jobs in a single pipeline since the publish job was being skipped.
=> test: Run jobs in a single pipeline

pkg/httpserver/server_test.go, pkg/rest/blockchainhandler/blockshandler.go, pkg/rest/blockchainhandler/firstvalidhandler.go, pkg/rest/blockchainhandler/firstvalidhandler_test.go, pkg/rest/blockchainhandler/model.go, pkg/rest/blockchainhandler/transactionshandler.go, pkg/rest/blockchainhandler/transactionshandler_test.go, pkg/rest/dcashandler/model.go, pkg/rest/dcashandler/retrievehandler.go, pkg/rest/dcashandler/retrievehandler_test.go, test/bddtests/features/blockchain-handler.feature, test/bddtests/features/dcas-handler.feature
=> chore: switch query parameters to kebab case

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: update sidetree-core (capability usage)

pkg/peer/config/peerconfig.go, pkg/peer/config/peerconfig_test.go, pkg/peer/mocks/restconfig.gen.go, pkg/peer/sidetreesvc/provider.go, test/bddtests/fixtures/config/fabric/core.yaml
=> feat: Add sidetree api token config

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
- revert to original pub key ID validation
Closes #273
=> chore: update sidetree-core - revert to original pub key ID validation

docs/api/README.md, docs/api/api.yml, docs/api/index.html
=> docs: initial Sidetree Open API

docs/api/api.yml
=> docs: add blocks schema

docs/api/api.yml
=> docs: fix cas endpoint

docs/api/api.yml
=> docs: add 401 to swagger for cas upload

pkg/peer/config/authtokenvalidator.go, pkg/peer/config/authtokenvalidator_test.go, test/bddtests/features/blockchain-handler.feature
=> fix: Validate both read and write tokens in config

pkg/peer/config/service.go, pkg/peer/sidetreesvc/channelctrl_test.go, pkg/peer/sidetreesvc/restsvc.go, pkg/peer/sidetreesvc/restsvc_test.go, pkg/rest/sidetreehandler/config.go, pkg/rest/sidetreehandler/versionhandler.go, pkg/rest/sidetreehandler/versionhandler_test.go, test/bddtests/features/did-sidetree.feature
=> feat: Add REST endpoint for Sidetree version

ci/version_var.sh
=> chore: Change version to 0.1.4

pkg/rest/blockchainhandler/configblockhandler.go, pkg/rest/blockchainhandler/configblockhandler_test.go, test/bddtests/features/blockchain-handler.feature
=> chore: Rename endpoint from /configblock to /config-block

cmd/peer/go.sum, go.mod, go.sum, pkg/context/store/client.go, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core: model cleanup, optional service properties, logs
Closes #309
=> chore: Update sidetree-core (model, optional service props)

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
JWS model changed from struct to compact JWS string
Closes #319
=> chore: update sidetree-core (JWS model change)

cmd/peer/go.sum, go.mod, go.sum, pkg/observer/observer.go, test/bddtests/blockchain_steps.go, test/bddtests/features/blockchain-handler.feature, test/bddtests/go.mod, test/bddtests/go.sum
Anchor string (num of ops + anchor address) is stored on blockchain
Closes #334
=> chore: updates sidetree-core (anchor string)

cmd/peer/go.sum, go.mod, go.sum, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Sidetree-core has been updated with:
- common batch file validations
Closes #346
=> chore: update sidetree-core (common batch validations)

cmd/chaincode/txn/txn.go, cmd/chaincode/txn/txn_test.go
- anchorBatch is not used, plus logic in it is no longer valid
Closes #354
=> chore: Remove unused function anchorBatch

cmd/peer/go.sum, go.mod, go.sum, pkg/context/common/provider.go, pkg/context/store/client.go, pkg/context/store/client_test.go, pkg/context/store/provider_test.go, pkg/mocks/operationstore.gen.go, pkg/rest/filehandler/validator_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Changes include:
- anchored operation (smallest subset of operation data to be stored into operation store)
Closes #370
=> chore: update sidetree-core (anchor operation)

cmd/peer/go.mod, cmd/peer/go.sum, go.mod, go.sum, test/bddtests/fixtures/config/fabric/invalid-hash-algorithm.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_4.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_5.json, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core; add signature and key algorithms configuration/validation
Closes #386
=> chore: update sidetree-core (add signature/key algorithms validation)

cmd/peer/go.sum, go.mod, go.sum, pkg/context/protocol/client.go, pkg/context/protocol/client_test.go, pkg/peer/config/service_test.go, pkg/peer/config/sidetreevalidator.go, pkg/peer/config/sidetreevalidator_test.go, pkg/peer/init_test.go, pkg/peer/sidetreesvc/channelctrl_test.go, pkg/peer/sidetreesvc/context_test.go, pkg/peer/sidetreesvc/provider_test.go, test/bddtests/fixtures/config/client/protocol.json, test/bddtests/fixtures/config/fabric/invalid-hash-algorithm.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_4.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_5.json, test/bddtests/go.mod, test/bddtests/go.sum
Changes include:
- support for JsonWebKey2020
- rename protocol parameters
Closes #390
=> chore: update sidetree-core; JsonWebKey2020, rename protocol parameters

Makefile, cmd/peer/go.mod, cmd/peer/go.sum, go.mod, go.sum, pkg/peer/init_test.go, test/bddtests/features/blockchain-handler.feature, test/bddtests/features/dcas-handler.feature, test/bddtests/features/did-sidetree.feature, test/bddtests/features/discovery-handler.feature, test/bddtests/features/file-handler.feature, test/bddtests/features/sidetreetxn.feature, test/bddtests/fixtures/docker-compose-base.yml, test/bddtests/fixtures/fabric/config/configtx.yaml, test/bddtests/go.mod, test/bddtests/go.sum, test/bddtests/sidetreetxn_steps.go
This update includes access control for org-specific ledger config.
closes #395
=> chore: Update with latest fabric-peer-ext

cmd/peer/go.sum, go.mod, go.sum, pkg/config/config.go, pkg/peer/config/service_test.go, pkg/peer/sidetreesvc/context.go, pkg/peer/sidetreesvc/restsvc.go, pkg/peer/sidetreesvc/restsvc_test.go, test/bddtests/fixtures/config/fabric/did-trustbloc-config.yaml, test/bddtests/go.mod, test/bddtests/go.sum
- add parameter for configuring method context(s) and
- if configured add pass WithMethodContext() option to didvalidator.New()
Closes #394
=> chore: Add ability to configure method context

cmd/peer/go.sum, go.mod, go.sum, pkg/peer/fabriclogger.go, pkg/peer/init.go
=> chore: Register Fabric logging provider for edge-core logging

cmd/peer/go.mod, cmd/peer/go.sum, go.mod, go.sum
=> chore: Update to latest fabric-peer-ext

cmd/peer/go.mod, cmd/peer/go.sum, go.mod, go.sum
=> chore: Update to latest fabric-sdk-go and fabric-peer-ext

ci/version_var.sh
=> chore: Bump version to 0.1.5

cmd/peer/go.mod, cmd/peer/go.sum, go.mod, go.sum, pkg/peer/init_test.go, pkg/peer/mocks/statedb.go, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Update to latest fabric-peer-ext and fabric-sdk-go

cmd/peer/go.sum, go.mod, go.sum, pkg/httpserver/server_test.go, pkg/observer/observer_test.go, pkg/peer/config/sidetreevalidator.go, pkg/peer/config/sidetreevalidator_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/fixtures/config/client/protocol.json, test/bddtests/fixtures/config/fabric/invalid-hash-algorithm.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_4.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_5.json, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core:
- double hash JWK for commitment
Update sidetree configuration validation for V0
Closes #417
=> chore: update sidetree-core (double hash JWK for commitment)

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/features/step_definitions/sidetree_steps.js, test/bddtests/fixtures/docker-compose-base.yml, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core:
-- additional long form format
-- additional logging in processor
Closes #419
=> chore: update sidetree-core (additional long form format)

cmd/peer/go.sum, go.mod, go.sum, pkg/protocolversion/versions/v0_1/validator/fileidxvalidator_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/filehandler_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Update to latest sidetree-core:
-- added ability to specify multiple patches in helper
Closes #426
=> chore: update sidetree-core (add patches to helper)

cmd/peer/go.sum, go.mod, go.sum, pkg/peer/config/service_test.go, pkg/peer/sidetreesvc/restsvc.go, pkg/rest/sidetreehandler/config.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/fixtures/config/fabric/did-sidetree-config.json, test/bddtests/go.mod, test/bddtests/go.sum
Included:
- add configuration for namespace aliases
- update sidetree-core (support for cannonical ID)
- add sanity integration test for resolving DID document with alias
=> chore: add configuration for namespace aliases; canonical id

cmd/peer/go.sum, go.mod, go.sum, pkg/httpserver/server_test.go, pkg/observer/observer_test.go, pkg/peer/config/service_test.go, pkg/peer/config/sidetreevalidator_test.go, pkg/protocolversion/versions/v0_1/validator/validator.go, pkg/protocolversion/versions/v0_1/validator/validator_test.go, test/bddtests/features/did-sidetree.feature, test/bddtests/features/file-handler.feature, test/bddtests/fixtures/config/fabric/invalid-hash-algorithm.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1_1.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1_2.json, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core:
- add generic parameter for patches
Closes #442
=> chore: update sidetree-core; add generic parameter for patches

cmd/peer/go.sum, go.mod, go.sum, pkg/context/store/client.go, pkg/httpserver/server_test.go, pkg/mocks/operationhandler.gen.go, pkg/observer/observer_test.go, pkg/protocolversion/versions/v0_1/factory/factory.go, pkg/protocolversion/versions/v0_1/validator/fileidxvalidator.go, pkg/protocolversion/versions/v0_1/validator/fileidxvalidator_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Included:
- update sidetree-core version (SIP-2; model moved to versioned folder)
Closes #449
=> chore: update sidetree-core (SIP-2, versioned models)

cmd/peer/go.sum, go.mod, go.sum, pkg/httpserver/server_test.go, pkg/observer/observer_test.go, pkg/peer/init_test.go, pkg/protocolversion/versions/v0_1/validator/fileidxvalidator_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/filehandler_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core:
- version parsing of long-form did
- rename and version helper/client
Closes #451
=> chore: update sidetree-core (version parsing long-form did, helper)

cmd/peer/go.sum, go.mod, go.sum, pkg/context/store/client.go, pkg/rest/filehandler/transformer.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/blockchain-handler.feature, test/bddtests/features/did-sidetree.feature, test/bddtests/features/file-handler.feature, test/bddtests/fixtures/config/fabric/invalid-hash-algorithm.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1_1.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1_2.json, test/bddtests/go.mod, test/bddtests/go.sum
Included:
- JSON API changes according to style guide
Closes #453
=> chore: Update sidetree-core (JSON API changes according to style guide)

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core: optional @base context
Closes #460
=> chore: update sidetree-core (optional @base context)

go.mod, go.sum, pkg/context/blockchain/client.go, pkg/observer/notifier/notifier.go, pkg/observer/observer_test.go, pkg/observer/processor.go, pkg/rest/blockchainhandler/blockscanner.go, pkg/rest/blockchainhandler/firstValidScanner.go, test/bddtests/blockchain_steps.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/blockchain-handler.feature, test/bddtests/features/step_definitions/blockchain_steps.js, test/bddtests/filehandler_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
For anchor string: rename anchor address to core index file URI (spec change)
Closes #475
=> chore: update sidetree-core (rename anchor address)

ci/version_var.sh
=> chore: Increment version to 0.1.6

Makefile, ci/azure-pipelines.yml, ci/version_var.sh, images/fabric-peer/Dockerfile, test/bddtests/fixtures/.env
=> ci: migrate to ghcr

cmd/peer/go.sum, go.mod, go.sum, pkg/rest/filehandler/retrievehandler.go, pkg/rest/filehandler/retrievehandler_test.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum, test/bddtests/httpSteps.go
Update sidetree-core (align with did core)
Closes #499
=> chore: update sidetree-core (align with did core)

pkg/httpserver/server.go
=> fix: cors option

cmd/peer/go.sum, go.mod, go.sum, test/bddtests/features/did-sidetree.feature, test/bddtests/features/file-handler.feature, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1_1.json, test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1_2.json, test/bddtests/go.mod, test/bddtests/go.sum
Included:
- update to release sidetree-core
- add nonceSize parameter
Closes #511
=> chore: update sidetree-core, nonceSize

ci/version_var.sh
=> chore: Release 0.6.0
