trustbloc/sidetree-fabric

.golangci.yml
Makefile
scripts/check_lint.sh

Re-enabled check_lint with golanci-lint v1.20 which uses much less memory.
closes #62

chore: Use golangci-lint v1.20

---

test/bddtests/features/did-sidetree.feature
test/bddtests/features/sidetreetxn.feature
test/bddtests/features/step_definitions/sidetree_steps.js
test/bddtests/fixtures/config/client/config.yaml
test/bddtests/fixtures/config/sdk-client/config.yaml
test/bddtests/fixtures/docker-compose.yml
test/bddtests/sidetreetxn_steps.go

Added a BDD test to demonstrate recovery of document operations in the local DCAS store on a peer that was down during the time that the data was published.
closes #69

test: BDD test for document monitor and recovery

---

Makefile

Point to the latest fabric-cli-ext which works with both Mac and Linux.
closes #116

chore: Fix for fabric-cli-ext build on Mac

---

cmd/peer/go.mod
cmd/peer/go.sum
go.mod
go.sum
pkg/observer/monitor/dcasreader.go
pkg/observer/monitor/dcasreader_test.go
pkg/observer/monitor/monitor.go
pkg/observer/monitor/monitor_test.go
pkg/observer/monitor/monitorerr.go
pkg/observer/monitor/monitorerr_test.go
pkg/observer/monitor/operationstore.go
pkg/observer/monitor/operationstore_test.go
test/bddtests/features/did-sidetree.feature
test/bddtests/features/sidetreetxn.feature

The Monitor now differentiates between persistent errors and transient errors. A transient error is temporary and retries on the request should eventually succeed. A persistent error will always fail.
closes #140

fix: Monitor will retry only transient errors

---

go.mod
pkg/filehandler/model.go
pkg/filehandler/retrievehandler.go
pkg/filehandler/retrievehandler_test.go
pkg/filehandler/validator.go
pkg/filehandler/validator_test.go
pkg/peer/sidetreesvc/restsvc.go
scripts/build_fabric_cli.sh
test/bddtests/features/file-handler.feature
test/bddtests/features/step_definitions/filehandler_steps.js
test/bddtests/filehandler_steps.go

The format of the file index document was changed such that it has explicit fields (as opposed to just a map of key-value pairs). Also, a document validator was added to validate create and update operations of the file index document.
This change required that the file-handler BDD test be reverted back to using file-handler steps and not the fabric-cli, since using the fabric-cli causes a circular dependency (i.e. fabric-cli depends on a sidetree-fabric image for BDD tests).
closes #165

feat: Change structure of file index document

---

cmd/peer/go.mod
cmd/peer/go.sum
go.mod
go.sum
test/bddtests/features/did-sidetree.feature
test/bddtests/features/file-handler.feature
test/bddtests/features/sidetreetxn.feature
test/bddtests/fixtures/docker-compose.yml

The document and meta-data collections are changed to 'IMPLICIT-ORG' so that each org manages its own documents. Each org must have its own Observer.
closes #142

test: Use an implicit collection policy for document store

---

Makefile
images/fabric-peer/Dockerfile

- copies files from upstream fabric image rather than basing on it.
- allows GO_LDFLAGS to be specified.
- allows image name and tag to be overriden.

refactor: docker image on clean base.

---

cmd/peer/go.sum
go.mod
go.sum
pkg/filehandler/validator_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/features/did-sidetree.feature
test/bddtests/filehandler_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Sidetree-core has been updated with two new features:
-- add/remove public keys patch
-- add/remove service endpoints patch
Add tests for both scenarios, update unit-tests
Closes #192

feat: Add/remove public keys and service endpoints

---

pkg/peer/sidetreesvc/channelctrl.go
pkg/peer/sidetreesvc/channelctrl_test.go

Store the ID of the config update transaction and use it to ignore other updates for the same transaction.
closes #196

fix: Restart services only once per config update transaction

---

ci/azure-pipelines.yml
cmd/peer/go.mod
cmd/peer/go.sum
go.mod
go.sum
test/bddtests/bddtests_test.go
test/bddtests/features/did-sidetree.feature
test/bddtests/features/file-handler.feature
test/bddtests/features/sidetreetxn.feature
test/bddtests/fixtures/config/fabric/mychannel-org1-config.json
test/bddtests/fixtures/config/fabric/mychannel-org2-config.json
test/bddtests/fixtures/config/fabric/yourchannel-org1-config.json
test/bddtests/fixtures/config/fabric/yourchannel-org2-config.json
test/bddtests/fixtures/config/sdk-client/config.yaml
test/bddtests/fixtures/docker-compose-base.yml
test/bddtests/fixtures/docker-compose.yml
test/bddtests/fixtures/fabric/config/configtx.yaml
test/bddtests/fixtures/fabric/config/cryptogen.yaml

- Added another peer to each org so that there are two endorsers and one committer
- The sidetree-observer and sidetree-monitor roles were set to the committer, since both roles require writes to the DB
- Caching was turned off since there's a potential bug (https://github.com/trustbloc/fabric-peer-ext/issues/382)
closes #173

test: Use cluster mode in BDD test for peers

---

cmd/peer/go.mod
cmd/peer/go.sum
go.mod
go.sum
pkg/rest/blockchainhandler/blockchainscanner.go
pkg/rest/blockchainhandler/blockchainscanner_test.go
pkg/rest/blockchainhandler/blockiterator.go
pkg/rest/blockchainhandler/blockiterator_test.go
pkg/rest/blockchainhandler/blockscanner.go
pkg/rest/blockchainhandler/blockscanner_test.go
pkg/rest/blockchainhandler/transactionshandler.go

The blockchain scanner now accepts a block iterator and a block scanner so that custom logic may be passed in.
closes #227

refactor: Refactored blockchain scanner to allow for custom iterators/scanners

---

pkg/httpserver/server_test.go
pkg/rest/blockchainhandler/firstValidScanner.go
pkg/rest/blockchainhandler/firstValidScanner_test.go
pkg/rest/blockchainhandler/model.go
pkg/rest/blockchainhandler/transactionshandler.go
pkg/rest/blockchainhandler/transactionshandler_test.go
pkg/rest/dcashandler/model.go
pkg/rest/dcashandler/retrievehandler.go
pkg/rest/dcashandler/retrievehandler_test.go
test/bddtests/features/blockchain-handler.feature
test/bddtests/features/dcas-handler.feature

updates the blockchain and dcas REST API to use underscores as
the word separator.

chore: blockchain and dcas handlers underscores

---

cmd/peer/go.sum
go.mod
go.sum
pkg/httpserver/server_test.go
pkg/peer/init_test.go
test/bddtests/bddtests_test.go
test/bddtests/features/blockchain-handler.feature
test/bddtests/features/dcas-handler.feature
test/bddtests/features/did-sidetree.feature
test/bddtests/features/e2e.feature
test/bddtests/features/sidetreetxn.feature
test/bddtests/fixtures/config/fabric/invalid-blockchainhandler-config.json
test/bddtests/fixtures/config/fabric/mychannel-blockchainhandler-config.yaml
test/bddtests/fixtures/config/fabric/mychannel-dcashandler-config.yaml
test/bddtests/fixtures/config/fabric/mychannel-org1-config.json
test/bddtests/fixtures/config/fabric/mychannel-org1-dcashandler-config.json
test/bddtests/fixtures/config/fabric/mychannel-org2-config.json
test/bddtests/fixtures/config/fabric/mychannel-org2-dcashandler-config.json
test/bddtests/fixtures/config/fabric/mychannel-sidetree-config-org1.json
test/bddtests/fixtures/config/fabric/mychannel-sidetree-config-org2.json
test/bddtests/go.mod
test/bddtests/go.sum

Renamed the resolutions endpoint to /identifiers and the base path of all Sidetree endpoints was changed to /sidetree/0.0.1.
closes #240
closes #241

chore: Renamed resolution endpoint and base path of endpoints

---

cmd/peer/go.sum
go.mod
go.sum
pkg/rest/filehandler/validator_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Sidetree core has been updated:
- remove 'replace' patch
- init state params order
Closes #253

chore: Update sidetree-core - remove replace patch

---

pkg/peer/config/blockchainhandlervalidator.go
pkg/peer/sidetreesvc/channelctrl.go
pkg/peer/sidetreesvc/channelctrl_test.go
pkg/rest/blockchainhandler/blockchaininfohandler.go
pkg/rest/blockchainhandler/blockchaininfohandler_test.go
pkg/rest/blockchainhandler/config.go
pkg/rest/blockchainhandler/firstvalidhandler.go
pkg/rest/blockchainhandler/handler.go
pkg/rest/blockchainhandler/model.go
pkg/rest/blockchainhandler/timehandler.go
pkg/rest/blockchainhandler/transactionshandler.go
test/bddtests/features/blockchain-handler.feature

Added a REST endpoint that retrieves basic information about the blockchain, including current block time and hash, and previous block hash.
Also, moved common functions to a base handler struct.
closes #255

feat: Added blockchain/info REST handler

---

go.mod
pkg/peer/sidetreesvc/channelctrl.go
pkg/peer/sidetreesvc/channelctrl_test.go
pkg/rest/blockchainhandler/blockchaininfohandler.go
pkg/rest/blockchainhandler/blockshandler_test.go
pkg/rest/blockchainhandler/configblockhandler.go
pkg/rest/blockchainhandler/configblockhandler_test.go
pkg/rest/blockchainhandler/handler.go
pkg/rest/blockchainhandler/timehandler.go
pkg/rest/blockchainhandler/timehandler_test.go
test/bddtests/features/blockchain-handler.feature

Added a REST endpoint that retrieves a config block. If a hash is specified then the block for that hash is retrieved and the last config index is extracted from the metadata section of that block. This index is used to retrieve the config block.
If no hash is specified then the latest block in the chain is retrieved and the config block is retrieved using the last config index of that block.
By default the data sections (data and metadata) of the returned config block are encoded in JSON format. But if the data-encoding parameter is set to 'base64' or 'base64url' then the data sections are encoded in base64 or base64url respectively.
closes #220

feat: Added blockchain/configblock REST endpoint

---

cmd/peer/go.sum
go.mod
go.sum
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Included:
- add service patch validation
- pub key and service id validation
- initial document validation includes services
- validation of all patches when parsing operation deltas (before operation is accepted)
- remove public keys and remove services patch validation
Closes #267

chore: Update sidetree-core (service validation)

---

pkg/rest/authhandler/authhandler.go
pkg/rest/authhandler/authhandler_test.go
test/bddtests/features/blockchain-handler.feature

fix: Ensure that query params are propagated from auth handler

---

cmd/peer/go.mod
cmd/peer/go.sum
go.mod
go.sum
test/bddtests/did_sidetree_steps.go

Updated to the latest fabric-peer-ext that fixes a panic when reading blockchain checkpoint info.
Also added a fix for a minor bug in the BDD test.
closes #307

chore: Update to latest fabric-peer-ext

---

pkg/context/blockchain/client.go
pkg/context/cas/client.go
pkg/context/store/client.go

Errors related to DB reads/writes are marked as transient so that the Observer may retry at a later time.
closes #310

fix: Retry on DB errors in Observer

---

pkg/context/operationqueue/leveldbqueue.go
pkg/context/operationqueue/leveldbqueue_test.go

The keys to be deleted are saved in a slice, but LevelDB reuses the key buffer in each iteration and therefore the key buffer changes. This fix adds a copy of the key to the slice.
closes #316

fix: Fix LevelDB operation queue delete

---

Makefile
pkg/common/transienterr/transienterr.go
pkg/common/transienterr/transienterr_test.go
pkg/config/config.go
pkg/context/blockchain/client.go
pkg/context/cas/client.go
pkg/context/store/client.go
pkg/observer/dcasreader.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/peer/config/sidetreepeervalidator.go
test/bddtests/fixtures/config/fabric/sidetree-config.json
test/bddtests/go.sum

Added new fields to metadata in order to keep track of failures when processing blocks. The following fields were added:
- LastTxNumProcessed: The last transaction within the block that was processed
- LastErrorCode: The error code that was received processing the last transaction
- FailedAttempts: The number of failed attempts processing the transaction
Also added a field to the Observer configuration:
- MaxAttempts: The maximum number of attempts to process a transaction. When a transient error occurs then a retry is attempted at the next scheduled interval. After processing has failed MaxAttempts times then the batch is lost and processing continues at the next transaction in the block.
closes #318

feat: Keep track of failures in Observer metadata

---

cmd/peer/go.sum
go.mod
go.sum
pkg/context/operationqueue/leveldbqueue.go
pkg/context/operationqueue/leveldbqueue_test.go
test/bddtests/go.mod
test/bddtests/go.sum

The Remove function of the LevelDB operation queue no longer returns the removed operations - just the number of operations removed.
closes #324

refactor: Refactored Remove function in operation queue

---

cmd/chaincode/txn/txn.go
cmd/chaincode/txn/txn_test.go
cmd/peer/go.sum
go.mod
go.sum
pkg/context/blockchain/client.go
pkg/context/blockchain/client_test.go
pkg/context/context.go
pkg/observer/common/constants.go
pkg/observer/notifier/notifier.go
pkg/observer/notifier/notifier_test.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/rest/blockchainhandler/blockchainscanner_test.go
pkg/rest/blockchainhandler/blockscanner.go
pkg/rest/blockchainhandler/blockscanner_test.go
pkg/rest/blockchainhandler/firstValidScanner.go
pkg/rest/blockchainhandler/firstValidScanner_test.go
pkg/rest/blockchainhandler/firstvalidhandler_test.go
pkg/rest/blockchainhandler/transactionshandler_test.go
test/bddtests/blockchain_steps.go
test/bddtests/features/blockchain-handler.feature
test/bddtests/go.mod
test/bddtests/go.sum

Updated:
-- blockchain client to include namespace during transaction
-- txn cc to include additional parameter
-- observer to parse transaction info
-- rest api to parse transaction info
Closes #338

chore: Add namespace to Sidetree transaction

---

cmd/peer/go.sum
go.mod
go.sum
pkg/httpserver/server_test.go
pkg/observer/observer.go
pkg/observer/observer_test.go
pkg/observer/operationfilter/operationfilter.go
pkg/observer/operationfilter/operationfilter_test.go
pkg/peer/sidetreesvc/restsvc.go
pkg/rest/filehandler/validator.go
pkg/rest/filehandler/validator_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/filehandler_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Sidetree core has been updated:
- generate recovery and update commitments from corresponding public JWK during create
- add update key to update request
- add recovery key for deactivate and recover requests
- validate keys against previously provided commitments
- validate signature against passed in keys
- return update and recovery commitments in resolution result metadata (remove recovery key and operation keys)
Closes #348

chore: update sidetree core (commitment changes)

---

cmd/chaincode/cas/client_test.go
cmd/chaincode/doc/doc.go
cmd/peer/go.sum
go.mod
go.sum
pkg/context/protocol/client.go
pkg/context/protocol/client_test.go
pkg/context/store/client.go
pkg/peer/config/service_test.go
pkg/peer/mocks/protocolclient.gen.go
test/bddtests/fixtures/config/client/protocol.json
test/bddtests/fixtures/config/fabric/mychannel-consortium-config.json
test/bddtests/fixtures/config/fabric/yourchannel-consortium-config.json
test/bddtests/go.mod
test/bddtests/go.sum

Sidetree core updates:
- add function to retrieve protocol by transaction (block) number
Add implementation of this function to fabric protocol client.

chore: Update sidetree-core (get protocol by txn number)

---

test/bddtests/features/blockchain-handler.feature
test/bddtests/features/dcas-handler.feature
test/bddtests/features/did-sidetree.feature
test/bddtests/features/discovery-handler.feature
test/bddtests/features/file-handler.feature
test/bddtests/features/sidetreetxn.feature
test/bddtests/features/step_definitions/common_steps.js
test/bddtests/fixtures/fabric/config/configtx.yaml
test/bddtests/go.mod
test/bddtests/go.sum

The channel capabilities were set to v2_0 and the BDD tests were updated to use chaincode lifecycle.
closes #381

test: Switch BDD test to Fabric 2 capabilities

---

cmd/peer/go.sum
go.mod
go.sum
test/bddtests/filehandler_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Update to latest sidetree-core. Changes included:
- removed "ops" purpose
- if applying patch fails we should continue to the next patch
- removed validation of optional service parameters
- fixed 'resolution loops indefinitely when operation's commitment equals next operation commitment'
Also, there is no longer need to insert update key in the doc for filehandler (removed functionality)
Closes #392

chore: update sidetree-core

---

cmd/peer/go.sum
go.mod
go.sum
pkg/context/context.go
pkg/context/context_test.go
pkg/context/protocol/client.go
pkg/context/protocol/client_test.go
pkg/peer/mocks/protocolclient.gen.go
pkg/peer/sidetreesvc/channelctrl_test.go
pkg/peer/sidetreesvc/context.go
pkg/peer/sidetreesvc/context_test.go
pkg/peer/sidetreesvc/provider.go
pkg/peer/sidetreesvc/provider_test.go
test/bddtests/go.mod
test/bddtests/go.sum

The implementation of the protocol client function, Current(), is now based on the current blockchain time (block number).
closes #412

fix: Protocol client Current() uses current block number

---

cmd/peer/go.sum
go.mod
go.sum
pkg/context/blockchain/client.go
pkg/context/blockchain/client_test.go
pkg/context/operationqueue/leveldbqueue.go
pkg/context/operationqueue/leveldbqueue_test.go
pkg/context/store/client.go
pkg/observer/common/constants.go
pkg/observer/observer.go
pkg/peer/mocks/batchwriter.gen.go
test/bddtests/go.mod
test/bddtests/go.sum

Update to latest sidetree-core-go which persists the protocol genesis time with each operation so that the operation is consistently processed with the same protocol version at each stage, i.e. batch writer, observer, and resolver.
closes #429

chore: Update to latest sidetree-core-go

---

pkg/peer/sidetreesvc/channelctrl.go
pkg/rest/filehandler/resolveindexhandler.go
pkg/rest/filehandler/resolveindexhandler_test.go
pkg/rest/filehandler/updateindexhandler.go
pkg/rest/filehandler/updateindexhandler_test.go
test/bddtests/features/file-handler.feature

The file paths for retrieve and update handlers are now prefixed with /identifiers and /operations respectively. Previously there was no prefix and therefore the /version endpoint was being ignored and the /version request was directed to the retrieve handler. This change makes the file endpoint consistent with the DID endpoints.
Also added a BDD test for file version.
closes #433

chore: Change file handler path to be consistent with DID

---

pkg/rest/filehandler/transformer.go
pkg/rest/filehandler/transformer_test.go

There is no need for generic document to have public keys in the document. The requirement for update key to be part of the document has been removed couple of months ago. This is leftover code - not used any more.
Closes #455

chore: Remove public keys processing from filehandler transformer

---

cmd/chaincode/doc/doc.go

The field name, unique_suffix, was changed to, uniqueSuffix.
closes #463

fix: Updated the CouchDB index for document store

---

pkg/rest/dcashandler/retrievehandler.go
pkg/rest/dcashandler/retrievehandler_test.go
test/bddtests/features/dcas-handler.feature

If the URL for cas does not contain the parameter, max-size=n, then HTTP 400 (bad request) is returned.
closes #462

fix: Return HTTP 400 when max-size not specified in cas URL

---

pkg/config/config.go
pkg/peer/config/service_test.go
pkg/peer/mocks/protocolversionfactory.gen.go
pkg/peer/sidetreesvc/context.go
pkg/peer/sidetreesvc/context_test.go
pkg/protocolversion/factoryregistry/factoryregistry.go
pkg/protocolversion/factoryregistry/factoryregistry_test.go
pkg/protocolversion/factoryregistry/mocks/protocolfactory.gen.go
pkg/protocolversion/versions/v0_1/factory/factory.go
pkg/protocolversion/versions/v0_1/factory/factory_test.go

Enable the following properties for document transformer:
- method context configuration
- @base property (new)
Closes #480

chore: add method context and enable @base configuration

---

cmd/peer/go.sum
go.mod
go.sum
pkg/context/protocol/client_test.go
pkg/httpserver/server_test.go
pkg/observer/observer_test.go
pkg/peer/config/service_test.go
pkg/peer/config/sidetreevalidator_test.go
pkg/peer/init_test.go
pkg/peer/sidetreesvc/channelctrl_test.go
pkg/peer/sidetreesvc/context_test.go
pkg/peer/sidetreesvc/provider_test.go
pkg/protocolversion/versions/v0_1/validator/fileidxvalidator_test.go
pkg/protocolversion/versions/v0_1/validator/validator.go
pkg/protocolversion/versions/v0_1/validator/validator_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/features/did-sidetree.feature
test/bddtests/features/file-handler.feature
test/bddtests/filehandler_steps.go
test/bddtests/fixtures/config/client/protocol.json
test/bddtests/fixtures/config/fabric/invalid-hash-algorithm.json
test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1.json
test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1_1.json
test/bddtests/fixtures/config/fabric/sidetree-protocol-v0_1_2.json
test/bddtests/go.mod
test/bddtests/go.sum

Complete SIP-1:
- add reveal value in update, reveal, deactivate operations
- support multiple multi-hashing algorithms in protocol
- remove max proof size protocol parameter
Also, added REST API check to fail create if applying patches results in an empty document (due to an error or invalid usage)
Closes #493

chore: update sidetree-core (reveal value added to requests)

---

cmd/peer/go.sum
go.mod
go.sum
pkg/context/blockchain/client.go
pkg/context/blockchain/client_test.go
pkg/context/context.go
pkg/context/context_test.go
pkg/mocks/operationhandler.gen.go
pkg/peer/mocks/batchcontext.gen.go
test/bddtests/features/did-sidetree.feature
test/bddtests/go.mod
test/bddtests/go.sum

Included:
- deactivate no longer returns 410
- anchor origin
- anchor times (from/until) along with new optional protocol parameter
Closes #503

chore: update sidetree-core: anchor times/origin, deactivate
